CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(80) UNIQUE NOT NULL,
	password VARCHAR(120) NOT NULL,
	is_admin BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE admins (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE profiles (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    bio TEXT,
    profile_image TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);


CREATE TABLE areas (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	is_private BOOLEAN DEFAULT FALSE
);


CREATE TABLE threads (
	id SERIAL PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	area_id INT NOT NULL,
	FOREIGN KEY (area_id) REFERENCES areas (id) ON DELETE CASCADE
);


CREATE TABLE messages (
	id SERIAL PRIMARY KEY,
	content TEXT,
	thread_id INT NOT NULL,
	user_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	FOREIGN KEY (thread_id) REFERENCES threads (id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
